server:
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: authserver
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



logging:
  level:
    org:
      springframework:
        security: TRACE
